Record.create(artist: 'Ed Sheeran', album: 'Bad Habits', year: 2021, condition: 'like new')
Record.create(artist: 'Taylor Swift', album: 'Folklore', year: 2020, condition: 'good')
Record.create(artist: 'Borns', album: 'Electric Love', year: 2015, condition: 'fair')
Record.create(artist: 'Electric Light Orchestra', album: 'Out of the Blue', year: 1977, condition: 'like new')
Record.create(artist: 'Bright Eyes', album: 'Lifted or The Story Is in the Soil, Keep Your Ear to the Ground', year: 2002, condition: 'fair')
Record.create(artist: 'Jimmy Eat World', album: 'Chase This Light', year: 2007, condition: 'broken')
Record.create(artist: 'Fall Out Boy', album: 'American Beauty', year: 2015, condition: 'fair')
Record.create(artist: 'Magic Giant', album: 'In The Windo', year: 2017, condition: 'like new')
Record.create(artist: 'Something Corporate', album: 'Leaving Through The Window', year: 2002, condition: 'good')
Record.create(artist: 'Spoon', album: 'They Want My Soul', year: 2014, condition: 'good')
Record.create(artist: 'The Postal Service', album: 'Give Up', year: 2003, condition: 'fair')
Record.create(artist: 'Weezer', album: 'The Blue Album', year: 1994, condition: 'good')